#?????? ?? -> ???? 8080
server:
  port: 9090

# database ?? ??
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: simple_user
    password: pjc0129

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml